name: main

on:
  push:
    branches:
      - main

env:
  DEPLOYMENT_REGION: ap-southeast-2
  STATE_S3_BUCKET: ${{ secrets.BUCKET_TF_STATE }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      
      - name: Install Dependencies
        run: pip install -r get-function/requirements.txt
        
      - name: Set AWS Region
        run: echo "AWS_REGION=ap-southeast-2" >> $GITHUB_ENV

      - name: Test get-function
        run: cd get-function && python -m unittest test.py

      - name: Test put-function
        run: cd get-function && python -m unittest test.py


  build-deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Set up AWS SAM
        uses: aws-actions/setup-sam@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-southeast-2

      - name: Build SAM Application
        run: sam build
        working-directory: cloud-resume-challenge

      - name: Deploy SAM Application
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
        working-directory: cloud-resume-challenge